Category.create!([
  {name: "Mac and Cheese", description: "Any kind of Mac and Cheese you might imagine. None of these other categories are needed, really, are they?"},
  {name: "Italian", description: "When the moon hits your eye like a big pizza pie..."},
  {name: "Mexican", description: "Donde esta?"},
  {name: "American Traditional", description: "Can you say Biscuits and Gravy? Because I can. I can say it very, very well."},
  {name: "Indian", description: "Spicy and a little dangerous. Just like you like it."},
  {name: "German", description: "Ummmmmmm. Right."},
  {name: "English", description: "Fish and Chips. Bangers and Mash. That sort of thing. Mate!"},
  {name: "Bear Grylls", description: "Only for the most adventurous. A stomach made of kevlar is strongly recommended."}
])
cat1 = Category.first
catid = cat1.id
cat2 = Category.find(catid + 1)
cat3 = Category.find(catid + 2)
cat4 = Category.find(catid + 3)
cat5 = Category.find(catid + 4)
cat6 = Category.find(catid + 5)
cat7 = Category.find(catid + 6)
cat8 = Category.find(catid + 7)

#Category::HABTM_Recipes.create!([
#  {category_id: 1, recipe_id: 1},
#  {category_id: 4, recipe_id: 2},
#  {category_id: 3, recipe_id: 3},
#  {category_id: 8, recipe_id: 4},
#  {category_id: 2, recipe_id: 5},
#  {category_id: 4, recipe_id: 6},
#  {category_id: 7, recipe_id: 7},
#  {category_id: 4, recipe_id: 8},
#  {category_id: 1, recipe_id: 9},
#  {category_id: 8, recipe_id: 10}
#])
Ingredient.create!([
  {name: "Macaroni noodles", quantity: 1.0, unit_of_measurement: "packet", description: nil},
  {name: "Milk", quantity: 0.5, unit_of_measurement: "cup", description: nil},
  {name: "Butter", quantity: 2.0, unit_of_measurement: "tablespoon", description: nil},
  {name: "Ice Cream", quantity: 3.0, unit_of_measurement: "Pint", description: nil},
  {name: "Tortilla", quantity: 5.0, unit_of_measurement: "Shell", description: nil},
  {name: "Hamburger Meat", quantity: 5.0, unit_of_measurement: "Cup", description: nil},
  {name: "Shredded Cheese", quantity: 1.5, unit_of_measurement: "Cup", description: nil},
  {name: "Chopped Tomato", quantity: 1.0, unit_of_measurement: "Tomato", description: nil},
  {name: "Shredded Lettuce", quantity: 0.5, unit_of_measurement: "Cup", description: nil},
  {name: "Hot Sauce", quantity: 3.0, unit_of_measurement: "Tablespoon", description: nil},
  {name: "Tortilla", quantity: 5.0, unit_of_measurement: "Shell", description: nil},
  {name: "Hamburger Meat", quantity: 5.0, unit_of_measurement: "Cup", description: nil},
  {name: "Shredded Cheese", quantity: 1.5, unit_of_measurement: "Cup", description: nil},
  {name: "Chopped Tomato", quantity: 1.0, unit_of_measurement: "Tomato", description: nil},
  {name: "Shredded Lettuce", quantity: 0.5, unit_of_measurement: "Cup", description: nil},
  {name: "Hot Sauce", quantity: 3.0, unit_of_measurement: "Tablespoon", description: nil},
  {name: "Tortilla", quantity: 5.0, unit_of_measurement: "Shell", description: nil},
  {name: "Hamburger Meat", quantity: 5.0, unit_of_measurement: "Cup", description: nil},
  {name: "Shredded Cheese", quantity: 1.5, unit_of_measurement: "Cup", description: nil},
  {name: "Chopped Tomato", quantity: 1.0, unit_of_measurement: "Tomato", description: nil},
  {name: "Shredded Lettuce", quantity: 0.5, unit_of_measurement: "Cup", description: nil},
  {name: "Hot Sauce", quantity: 3.0, unit_of_measurement: "Tablespoon", description: nil},
  {name: "Tortilla", quantity: 5.0, unit_of_measurement: "Shell", description: nil},
  {name: "Hamburger Meat", quantity: 5.0, unit_of_measurement: "Cup", description: nil},
  {name: "Shredded Cheese", quantity: 1.5, unit_of_measurement: "Cup", description: nil},
  {name: "Chopped Tomato", quantity: 1.0, unit_of_measurement: "Tomato", description: nil},
  {name: "Shredded Lettuce", quantity: 0.5, unit_of_measurement: "Cup", description: nil},
  {name: "Hot Sauce", quantity: 3.0, unit_of_measurement: "Tablespoon", description: nil},
  {name: "Macaroni noodles", quantity: 1.0, unit_of_measurement: "packet", description: nil},
  {name: "Milk", quantity: 0.5, unit_of_measurement: "cup", description: nil},
  {name: "Butter", quantity: 2.0, unit_of_measurement: "tablespoon", description: nil},
  {name: "Bug", quantity: 1.0, unit_of_measurement: "Bug", description: nil},
  {name: "Dough", quantity: 1.0, unit_of_measurement: "lb", description: nil},
  {name: "Tomato Sauce", quantity: 1.0, unit_of_measurement: "jar", description: nil},
  {name: "Cheese", quantity: 1.0, unit_of_measurement: "lb", description: nil},
  {name: "Ground Hamburger", quantity: 1.0, unit_of_measurement: "lb", description: nil},
  {name: "Sliced Pepperoni", quantity: 0.5, unit_of_measurement: "lb", description: nil},
  {name: "Bread", quantity: 2.0, unit_of_measurement: "slice", description: nil},
  {name: "Peanut Butter", quantity: 5.0, unit_of_measurement: "Tablespoon", description: nil},
  {name: "Jelly", quantity: 5.0, unit_of_measurement: "Tablespoon", description: nil},
  {name: "Cod", quantity: 2.0, unit_of_measurement: "filet", description: nil},
  {name: "French Fries", quantity: 2.0, unit_of_measurement: "handfull", description: nil},
  {name: "Meat", quantity: 5.0, unit_of_measurement: "filet", description: nil},
  {name: "Butter", quantity: 2.0, unit_of_measurement: "tablespoon", description: nil},
  {name: "Macaroni noodles", quantity: 1.0, unit_of_measurement: "packet", description: nil},
  {name: "Butter", quantity: 2.0, unit_of_measurement: "tablespoon", description: nil},
  {name: "Milk", quantity: 0.25, unit_of_measurement: "cup", description: nil},
  {name: "Cheese sauce", quantity: 1.0, unit_of_measurement: "packet", description: nil},
  {name: "Leaf", quantity: 1.0, unit_of_measurement: "leaf", description: nil},
  {name: "Snake", quantity: 1.0, unit_of_measurement: "snake", description: nil}
])
Ingredient::HABTM_Recipes.create!([
  {ingredient_id: 1, recipe_id: 1},
  {ingredient_id: 2, recipe_id: 1},
  {ingredient_id: 3, recipe_id: 1},
  {ingredient_id: 4, recipe_id: 2},
  {ingredient_id: 5, recipe_id: 3},
  {ingredient_id: 6, recipe_id: 3},
  {ingredient_id: 7, recipe_id: 3},
  {ingredient_id: 8, recipe_id: 3},
  {ingredient_id: 9, recipe_id: 3},
  {ingredient_id: 10, recipe_id: 3},
  {ingredient_id: 32, recipe_id: 4},
  {ingredient_id: 33, recipe_id: 5},
  {ingredient_id: 34, recipe_id: 5},
  {ingredient_id: 35, recipe_id: 5},
  {ingredient_id: 36, recipe_id: 5},
  {ingredient_id: 37, recipe_id: 5},
  {ingredient_id: 38, recipe_id: 6},
  {ingredient_id: 39, recipe_id: 6},
  {ingredient_id: 40, recipe_id: 6},
  {ingredient_id: 41, recipe_id: 7},
  {ingredient_id: 42, recipe_id: 7},
  {ingredient_id: 43, recipe_id: 8},
  {ingredient_id: 44, recipe_id: 8},
  {ingredient_id: 45, recipe_id: 9},
  {ingredient_id: 46, recipe_id: 9},
  {ingredient_id: 47, recipe_id: 9},
  {ingredient_id: 48, recipe_id: 9},
  {ingredient_id: 49, recipe_id: 9},
  {ingredient_id: 50, recipe_id: 10}
])
Recipe.create!([
  {name: "Mac and Cheese", description: "Manna from heaven. Seriously. What's better than Mac and Cheese?", instructions: "Dump them in the boiling water, then dump in the cheese packet and milk and maybe throw in some butter and eat it all and try not to feel bad about it", image: File.open(File.join(Rails.root, "public/uploads/recipe/image/1/max_and_cheese.jpeg")), categories: [cat1]},
  {name: "Ice Cream", description: "Do you honestly not know what ice cream is?", instructions: "Buy some pints, open the pints, continue to eat until you feel better", image: File.open(File.join(Rails.root, "public/uploads/recipe/image/2/ice_cream.jpeg")), categories: [cat4]},
  {name: "Tacos", description: "Meat, cheese, and maybe some other stuff wrapped in a crunchy tortilla, covered in hot sauce, and able to save your soul from eternal damnation with it's inherant goodness", instructions: "Mix it all up together, it doesn't matter how. It's gonna taste amazing regardless. Jam it in the shell and make sure to get as much of it on your shirt as possible while you're eating it.", image: File.open(File.join(Rails.root, "public/uploads/recipe/image/3/taco.jpeg")), categories: [cat3]},
  {name: "Big Giant Bug", description: "A big, ugly, nasty, disgusting bug. You wouldn't even want to touch it, let alone eat it. That's because you aren't Bear Grylls.", instructions: "Pick it up, cowboy up, and eat it.", image: File.open(File.join(Rails.root, "public/uploads/recipe/image/4/bear_grylls_bug.jpg")), categories: [cat8]},
  {name: "Pizza", description: "Hot or cold, fresh or old, it doesn't matter. It's so good. I want some right now, actually. Load it up with cheese, meat, whatever. Just don't put pineapple on it! What even is that?", instructions: "Make the dough and cool it, then slap it on the pan and flatten it out. Dump all of the ingredients onto it and bake it until it's done. If you're a pro, you can even hide some extra cheese in the crust.", image: File.open(File.join(Rails.root, "public/uploads/recipe/image/5/pizza.jpeg")), categories: [cat2]},
  {name: "PB & J", description: "Peanut butter and jelly is a classic. It's also sometimes all you can afford. Like when you're in college. Or when you're 6. But regardless of your age, the key is to not skimp on the jelly. You hear that Becky?! Don't bogart all the jelly!!", instructions: "Slather the PB and the J all over the bread, put the 2 peices together (sticky side in, obviously), and eat like your 6, even if you're not.", image: File.open(File.join(Rails.root, "public/uploads/recipe/image/6/pbj.jpeg")), categories: [cat4]},
  {name: "Fish and Chips", description: "Battered and fried fish with fries. Those crazy and English and their \"chips\", am I right?!", instructions: "Grab some white fish, batter it up good, and fry it to make sure every bit of natural healthiness is right out. Do the same to some french fries, and then eat them together and ponder what it must be like for an English fish to be on the same plate as a French potato, and consider how awkward it might be if World War 2 comes up in conversation.", image: File.open(File.join(Rails.root, "public/uploads/recipe/image/7/fish_and_chips.jpeg")), categories: [cat7]},
  {name: "Steak!!", description: "It's the \"Bond, James Bond\" of food. It's just so, so good.", instructions: "Grab a HUGE handful of steaks and slap them on the grill and drop a few dollops of butter on each one and let it cook for a few minutes, then turn it over and give it another few minutes and try to literally dive into the grill in order to get at the meaty goodness quicker.", image: File.open(File.join(Rails.root, "public/uploads/recipe/image/8/steak.jpeg")), categories: [cat4]},
  {name: "Fancy Mac and Cheese", description: "It's mac and cheese, but with some shrubbery so that THEY CAN CHARGE YOU MORE!!!!! Oh no's!!!!!!", instructions: "Make it the same way you'd make any other mac and cheese. Then drop a leaf on top of it and take a picture of it like it's some amazing thing. Cool it buddy, it's just mac and cheese!", image: File.open(File.join(Rails.root, "public/uploads/recipe/image/9/fancy_mac.jpeg")), categories: [cat1]},
  {name: "Snake", description: "Unleash your inner honeybadger and tear into a snake. Or, you know, consider your life and safety and maybe don't? I dunno, your call. They did it in that one Indiana Jones movie and Harrison Ford is still alive, so how bad can it be?", instructions: "You're on your own here. Bear was a man and just tore into it - no cooking, nothing. If you are a man like Bear, then have at it. Otherwise, snake might not be for you.", image: File.open(File.join(Rails.root, "public/uploads/recipe/image/10/bear_snake.jpeg")), categories: [cat8]}
])
#Recipe::HABTM_Ingredients.create!([
#  {ingredient_id: 1, recipe_id: 1},
#  {ingredient_id: 2, recipe_id: 1},
#  {ingredient_id: 3, recipe_id: 1},
#  {ingredient_id: 4, recipe_id: 2},
#  {ingredient_id: 5, recipe_id: 3},
#  {ingredient_id: 6, recipe_id: 3},
#  {ingredient_id: 7, recipe_id: 3},
#  {ingredient_id: 8, recipe_id: 3},
#  {ingredient_id: 9, recipe_id: 3},
#  {ingredient_id: 10, recipe_id: 3},
#  {ingredient_id: 32, recipe_id: 4},
#  {ingredient_id: 33, recipe_id: 5},
#  {ingredient_id: 34, recipe_id: 5},
#  {ingredient_id: 35, recipe_id: 5},
#  {ingredient_id: 36, recipe_id: 5},
#  {ingredient_id: 37, recipe_id: 5},
#  {ingredient_id: 38, recipe_id: 6},
#  {ingredient_id: 39, recipe_id: 6},
#  {ingredient_id: 40, recipe_id: 6},
#  {ingredient_id: 41, recipe_id: 7},
#  {ingredient_id: 42, recipe_id: 7},
#  {ingredient_id: 43, recipe_id: 8},
#  {ingredient_id: 44, recipe_id: 8},
#  {ingredient_id: 45, recipe_id: 9},
#  {ingredient_id: 46, recipe_id: 9},
#  {ingredient_id: 47, recipe_id: 9},
#  {ingredient_id: 48, recipe_id: 9},
#  {ingredient_id: 49, recipe_id: 9},
#  {ingredient_id: 50, recipe_id: 10}
#])
#Recipe::HABTM_Categories.create!([
#  {category_id: 1, recipe_id: 1},
#  {category_id: 4, recipe_id: 2},
#  {category_id: 3, recipe_id: 3},
#  {category_id: 8, recipe_id: 4},
#  {category_id: 2, recipe_id: 5},
#  {category_id: 4, recipe_id: 6},
#  {category_id: 7, recipe_id: 7},
#  {category_id: 4, recipe_id: 8},
#  {category_id: 1, recipe_id: 9},
#  {category_id: 8, recipe_id: 10}
#])
